### ISSUE TITLE
Beta- Bernoulli bug

### ISSUE THREAD

**Issue by abojchevski** [blei-lab/edward#78] opened 2016-05-12 14:52 UTC
In the provided example of the Beta Bernoulli model if you change the line:

```
data = ed.Data(tf.constant((0, 1, 0, 0, 0, 0, 0, 0, 0, 1), dtype=tf.float32))
```

to

```
data = ed.Data(tf.constant((0, 1, 1, 1, 1, 1, 1, 0, 0, 1), dtype=tf.float32))
```

the following error is thrown:

```
ValueError: Domain error in arguments.
```

This only happens with the TensorFlow implementation (_tf.py) and not the numpy implementation (_np.py)

Any ideas why?

**Comment by abojchevski** [comment] 2016-05-12 14:55
For the numpy implementation it throws the same error with the following input:
```
data = ed.Data(np.array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
```

**Comment by dustinvtran** [comment] 2016-05-13 15:22
Hi @abojchevski, I'm unable to reproduce the error unfortunately. I checked the latest development version and also from 1.0.2 on PyPI. Can you provide more information about your installation?

**Comment by abojchevski** [comment] 2016-05-13 15:34
edward installed with
```
pip install -e "git+https://github.com/blei-lab/edward.git#egg=edward"
```
and
```
numpy                     1.11.0                   py35_0
tensorflow                0.8.0                     <pip>
```

**Comment by dustinvtran** [comment] 2016-05-13 15:38
Hmm interesting. I tried all of those and can't reproduce it. What operating system are you using? And is this particular configuration of 0's and 1's or does any change from the default configuration produce that error?

**Comment by abojchevski** [comment] 2016-05-13 15:49
Ubuntu 16.04.

Not just that combination. Some other ones as well. I first thought it was an edge case, but after trying some examples I couldn't find the pattern of the configuration which fail/pass.

It is also not immediate. So after some number of batches the params are updated to nan and hence the error.

**Comment by abojchevski** [comment] 2016-05-13 15:55
I also tryed passing more data as input
```np.random.binomial(1, 0.8, 1000)```
and changing the mini batches. In that case it doesn't fail as often but it still sometimes does.

And since in the example you have fixed seed when it does, it does so consistently.

**Comment by dustinvtran** [comment] 2017-07-03 20:13
Closing as we no longer use `ed.Data`.

**Closed by dustinvtran** 2017-07-03 20:13 UTC
Labels: Bug
