### ISSUE TITLE
binary accuracy

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#262] opened 2016-09-28 17:11 UTC
`ed.eval('binary_accuracy',[...])` evaluates to 1.0 when the Bernoulli mean is 0.5 irrespective of label. This can be missleading. Results (in terms of binary accuracy) seem great while your params are simply very close to 0.

**Comment by dustinvtran** [comment] 2016-09-28 19:05
That's interesting. So this is caused by `tf.round()` in `binary_accuracy()`, which always rounds 0.5 up to `1.0`. Should it round up or down randomly instead?

**Comment by nitishjoshi25** [comment] 2017-05-20 09:03
i was looking into this problem. `tf.round()` rounds `0.5` to `0` instead of rounding up to `1.0`.

**Comment by dustinvtran** [comment] 2017-05-23 21:44
Right. I think the easiest solution is to to do a random round if equal to 0.5. (using a tensorflow control flow op)

**Comment by dustinvtran** [comment] 2017-05-28 22:13
Fixed in #651.

**Closed by dustinvtran** 2017-05-28 22:13 UTC
Labels: Good first contribution
